# Generated by Django 3.2.3 on 2021-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bName', models.CharField(max_length=30)),
                ('bID', models.CharField(max_length=15)),
                ('bAuthor', models.CharField(max_length=20)),
                ('bYear', models.IntegerField()),
                ('bTotal', models.IntegerField(default=0)),
                ('bLeft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=30)),
                ('bSingleID', models.CharField(max_length=15)),
                ('uID', models.CharField(max_length=15)),
                ('applyDate', models.DateField(auto_now_add=True)),
                ('borrowDate', models.DateField()),
                ('presetDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('returnCondition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendBook',
            fields=[
                ('bID', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=30)),
                ('bAuthor', models.CharField(max_length=20)),
                ('bYear', models.IntegerField(default=0)),
                ('bTotal', models.IntegerField(default=1)),
                ('bReason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bID', models.CharField(max_length=15)),
                ('bSingleID', models.CharField(max_length=15)),
                ('bCondition', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uID', models.CharField(max_length=15)),
                ('uPWD', models.CharField(max_length=25)),
                ('uPhone', models.CharField(max_length=15)),
                ('uCharacter', models.BooleanField(default=False)),
            ],
        ),
    ]
