# Generated by Django 3.2.3 on 2021-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='bYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='applyDate',
            field=models.DateField(auto_now_add=True, verbose_name='申借日期'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowDate',
            field=models.DateField(blank=True, null=True, verbose_name='借书日期'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='presetDate',
            field=models.DateField(blank=True, null=True, verbose_name='规定还书日期'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='returnCondition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='returnDate',
            field=models.DateField(blank=True, null=True, verbose_name='实际还书日期'),
        ),
        migrations.AlterField(
            model_name='recommendbook',
            name='bReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
